# TODO: FROM命令でパブリックリポジトリからbase imageを取得.
# base imageはpythonを使用し, tagは3.6を指定する.

# TODO: WORKDIR命令で作業ディレクトリをday20に指定.

# TODO: COPY命令で作業ディレクトリにrequirements.txtをコピー.

# TODO: pipでrequirements.txtに記されたパッケージをインストール.
# TODO: pipのキャッシュを削除.

# TODO: 作業ディレクトリにday20をコピー.

# TODO: 環境変数を設定
# FLASK_APPはday20:appに設定
# FLASK_ENVはdevelopmentに設定
