help:
		@echo "Commands:"
# TODO: init, runについてドキュメンテーションを実装.

init:
# TODO: imageをbuildするコマンドを実装.
# imageの名前はday20とする.

run:
# TODO: containerを作成し, バックグラウンドでcontainerを実行するコマンドを実装.
# containerのポートをlocalhostのポートに割り当てる.
# containerの名前はday20とする.
# container実行時にサーバを起動する.
